[phases.setup]
nixPkgs = ["python311", "gcc", "libGL", "libGLU", "glib"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --workers 1 --threads 2 --timeout 120 --bind 0.0.0.0:$PORT"
